# render.yaml
services:
  - type: web
    name: mista-backend
    env: python
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn chat_backend:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - fromGroup: mista-secrets

cron:
  - job:
      name: clear-chat-history
      schedule: "0 0 * * *" # Run every day at midnight UTC
      command: "curl -X POST https://mista-backend.onrender.com/clear-chat"
    name: clear-chat-cron
